### ISSUE TITLE
List ratatui-compatible crates

### ISSUE THREAD

**Issue by holly-hacker** [ratatui-org/awesome-ratatui#8]
There are a lot of great ratatui-compatible crates but this repo only lists apps that use ratatui. Perhaps a section can be added to list these crates, or perhaps the repo could be renamed to `awesome-ratatui-apps` instead? Besides serving as an example, existing apps aren't as useful a resource to people building a ratatui app themselves.

**Comment by orhun** [comment]
Hello!

> ratatui-compatible crates

Can you give a couple of examples?

**Comment by holly-hacker** [comment]
Many can be found by browsing the `ratatui` keyword on the crates repository or through reverse dependencies:
- [tui-textarea](https://lib.rs/crates/tui-textarea)
- [ratatui-textarea](https://lib.rs/crates/ratatui-textarea)
- [ratatui-image](https://lib.rs/crates/ratatui-image)
- [tui-big-text](https://lib.rs/crates/tui-big-text)
- [tui-prompts](https://lib.rs/crates/tui-prompts)
- [tui-widget-list](https://lib.rs/crates/tui-widget-list)
- [tui-tree-widget](https://lib.rs/crates/tui-tree-widget)
- [tui-logger](https://lib.rs/crates/tui-logger)
- [tui-term](https://crates.io/crates/tui-term)
- [ansi-to-tui](https://lib.rs/crates/ansi-to-tui) and [color-to-tui](https://lib.rs/crates/color-to-tui)
- [tui-additions](https://lib.rs/crates/tui-additions)

Other libraries build on top of ratatui to provide their own abstractions:
- [widgetui](https://lib.rs/crates/widgetui)
- [tui-react](https://lib.rs/crates/tui-react)

Some of these may be out-of-date, but by adding them to the list they may attract community contributions to bring them back up to the latest version of ratatui.

**Comment by orhun** [comment]
Sounds good, I think we can add them under a new section called "libraries". Would you be interested in making a PR?

P.S. We have showcases for some of those 3rd widgets in our docs: https://ratatui.rs/showcase/third-party-widgets/

**Comment by holly-hacker** [comment]
Sure, I've opened #9
